import { type Restaurant, generateId } from "./storage"

export const shoreditchRestaurants: Omit<Restaurant, "id">[] = [
  {
    name: "Dishoom Shoreditch",
    link: "https://www.dishoom.com/shoreditch/",
    walkTime: 8,
    priceLevel: 2,
    tags: ["indian", "comfort", "brunch", "trendy"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Pizza East",
    link: "https://pizzaeast.com/",
    walkTime: 5,
    priceLevel: 2,
    tags: ["italian", "pizza", "casual", "quick"],
    dietaryOptions: ["vegetarian", "vegan"],
  },
  {
    name: "Blacklock Shoreditch",
    link: "https://www.theblacklock.com/",
    walkTime: 7,
    priceLevel: 2,
    tags: ["british", "meat", "comfort", "trendy"],
    dietaryOptions: ["gluten-free"],
  },
  {
    name: "Bistro Freddie",
    link: "https://www.bistrofreddie.com/",
    walkTime: 6,
    priceLevel: 3,
    tags: ["french", "bistro", "wine", "upscale"],
    dietaryOptions: ["vegetarian", "gluten-free"],
  },
  {
    name: "Hawksmoor Spitalfields",
    link: "https://thehawksmoor.com/locations/spitalfields/",
    walkTime: 10,
    priceLevel: 3,
    tags: ["british", "steak", "upscale", "special"],
    dietaryOptions: ["gluten-free"],
  },
  {
    name: "Grind Old Street",
    link: "https://grind.co.uk/",
    walkTime: 3,
    priceLevel: 2,
    tags: ["cafe", "brunch", "coffee", "quick", "casual"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Lantana Shoreditch",
    link: "https://www.lantanacafe.co.uk/",
    walkTime: 6,
    priceLevel: 2,
    tags: ["cafe", "healthy", "brunch", "australian"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "BoxPark Shoreditch",
    link: "https://www.boxpark.co.uk/shoreditch/",
    walkTime: 8,
    priceLevel: 2,
    tags: ["food-hall", "variety", "casual", "quick", "trendy"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free", "halal"],
  },
  {
    name: "Cecconi's Shoreditch",
    link: "https://www.cecconis.co.uk/shoreditch/",
    walkTime: 7,
    priceLevel: 3,
    tags: ["italian", "upscale", "venetian", "special"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Sticks'n'Sushi Shoreditch",
    link: "https://sticksnsushi.com/",
    walkTime: 6,
    priceLevel: 3,
    tags: ["japanese", "sushi", "upscale", "healthy"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "The Brush Grand Café",
    link: "https://www.thebrushcafe.com/",
    walkTime: 4,
    priceLevel: 2,
    tags: ["cafe", "british", "casual", "brunch"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Singburi",
    link: "https://www.singburi.co.uk/",
    walkTime: 9,
    priceLevel: 2,
    tags: ["thai", "spicy", "authentic", "casual"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Lagana",
    link: "https://lagana.co.uk/",
    walkTime: 8,
    priceLevel: 2,
    tags: ["greek", "flatbread", "mediterranean", "casual"],
    dietaryOptions: ["vegetarian", "gluten-free"],
  },
  {
    name: "One Club Row",
    link: "https://oneclubrow.com/",
    walkTime: 10,
    priceLevel: 2,
    tags: ["american", "burger", "casual", "comfort"],
    dietaryOptions: ["vegetarian", "gluten-free"],
  },
  {
    name: "EDO IZAKAYA",
    walkTime: 5,
    priceLevel: 2,
    tags: ["japanese", "izakaya", "sushi", "trendy"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Poppies Fish & Chips",
    link: "https://www.poppiesfishandchips.co.uk/",
    walkTime: 7,
    priceLevel: 2,
    tags: ["british", "fish-chips", "comfort", "casual"],
    dietaryOptions: ["gluten-free"],
  },
  {
    name: "Ozone Coffee Roasters",
    link: "https://www.ozonecoffee.co.uk/",
    walkTime: 10,
    priceLevel: 2,
    tags: ["cafe", "brunch", "coffee", "healthy"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Bao Shoreditch",
    link: "https://baolondon.com/",
    walkTime: 8,
    priceLevel: 2,
    tags: ["taiwanese", "bao", "trendy", "small-plates"],
    dietaryOptions: ["vegetarian", "vegan"],
  },
  {
    name: "Berber & Q Shawarma Bar",
    link: "https://www.berberandq.com/",
    walkTime: 9,
    priceLevel: 2,
    tags: ["middle-eastern", "shawarma", "casual", "spicy"],
    dietaryOptions: ["vegetarian", "vegan", "gluten-free", "halal"],
  },
  {
    name: "SAGARDI Basque",
    walkTime: 7,
    priceLevel: 3,
    tags: ["spanish", "basque", "steak", "upscale"],
    dietaryOptions: ["gluten-free"],
  },
]

export function seedShoreditchRestaurants(): Restaurant[] {
  return shoreditchRestaurants.map((r) => ({
    ...r,
    id: generateId(),
  }))
}
